services:
    # MySQL Database Service
    mysql:
        image: mysql:8.0
        container_name: kpi-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: kpi
            MYSQL_USER: kpiuser
            MYSQL_PASSWORD: kpipassword
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d
        networks:
            - kpi-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
            timeout: 20s
            retries: 10
            interval: 10s
            start_period: 40s

    # KPI Application Service
    kpi-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: kpi-application
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=mysql;Database=kpi;Uid=kpiuser;Pwd=kpipassword;SslMode=none;
        ports:
            - "8080:80"
        networks:
            - kpi-network
        volumes:
            - ./logs:/app/logs

networks:
    kpi-network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
